name: flutter_upi_helper_example
description: "Example app for the flutter_upi_helper package."
publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_upi_helper:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
