name: flutter_upi_helper
description: "A production-ready Flutter package for handling UPI payments in India. Easily launch major UPI apps and handle payment responses."
version: 1.0.0
homepage: https://github.com/harmishanaxistech-ship-it/UPI-Helper
repository: https://github.com/harmishanaxistech-ship-it/UPI-Helper.git
issue_tracker: https://github.com/harmishanaxistech-ship-it/UPI-Helper/issues

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
